"""Initial migration.

Revision ID: 9d69bfdd0670
Revises: 
Create Date: 2025-11-11 01:09:15.440744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d69bfdd0670'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False, comment='名称'),
    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False, comment='描述'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id', name='pk_demo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo')
    # ### end Alembic commands ###
